# Generated by Django 4.1.7 on 2023-03-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_items',
            field=models.ManyToManyField(blank=True, to='payments.invoiceitem'),
        ),
    ]
