# Generated by Django 4.1.7 on 2023-03-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_invoice_invoice_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
    ]
