# Generated by Django 3.2.14 on 2023-03-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_receptionistprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
