# Generated by Django 4.1.7 on 2023-03-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_patientprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
