# Generated by Django 4.1.7 on 2023-03-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(choices=[('Dept 1', 'Dept 1'), ('Dept 2', 'Dept 2')], max_length=20),
        ),
    ]
